export enum Entities {
  Role = 'Role',
  Permission = 'Permission',
  User = 'User',
  Photo = 'Photo',
  Admin = 'Admin',
  Teacher = 'Teacher',
  Statistics = 'Statistics',
  Wallet = 'Wallet',
  Course = 'Course',
  Video = 'Video',
  Apply = 'Apply',
  Question = 'Question',
  All = 'all',
}
